version: '3.7'

services:
  postgres:
    container_name: product_api_db
    image: postgres:latest
    environment:
      POSTGRES_USER: products
      POSTGRES_PASSWORD: products
      POSTGRES_DB: products
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - products
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI port
      - "4317:4317" # the open telemetry grpc port for sending traces
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

networks:
  products:
    driver: bridge