server:
  port: 8081

spring:
  application:
    name: price-fare
  profiles.active: local
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    platform: postgres
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products
    username: products
    password: products
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: tests
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS products
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate.ddl-auto: create



